# Generated by Django 6.0.3 on 2026-04-19 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
