# Generated by Django 6.0.3 on 2026-04-20 22:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_collaboraterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
